Unify build logic, sync with version catalogs, bump dependencies
Irineu333/SpeakTouch pull request #84
Opened 2023-11-04 23:49 UTC by PatrykMis

### Improvements

* unify versions of dependencies and sync with version catalogs
* bump dependencies
* small build code adjustments

2023-11-06 13:04 UTC, Irineu333 requested changes

2023-11-06 13:04 UTC, Irineu333 commented on buildSrc/settings.gradle.kts
I think it's better to put the license on all files.

``` kotlin
/*
 * File description.
 *
 * Copyright (C) 2023 Your Name.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

```

2023-11-06 14:35 UTC, Irineu333 commented
Thanks for updating the license-free files. I intended to do that later. This promotes security for whoever uses the code, from what I know of the law, whoever writes it automatically has all the rights to the code, the license is basically you giving up your rights. Code that is unlicensed for legal purposes is proprietary code.

2023-11-06 14:49 UTC, PatrykMis commented
The clause states about the software as a whole product, not an individual files. Observing it in practise, the software is Copyright © to you, thus I added the same in every file. I haven't touched files that are automatically generated by Android Studio, because they have no license so I asume they're in public domain. Regaldless of clause in any file, the repository clearly states being licensed as GPL v3, so I think it's not nessesary to clutter every file, but it's only my personal opinion.

2023-11-06 14:55 UTC, Irineu333 commented
I think I misunderstood the license then.  I thought that each file should have the copyright of whoever created it, giving away their rights.  Whoever modified it would essentially accept the terms.  Sorry for the confusion, I'll read it again.

2023-11-06 14:58 UTC, Irineu333 commented
I also believe that it is not necessary to put a license on generated files, they are probably under the Apache 2.0 license, right?

2023-11-06 15:00 UTC, PatrykMis commented
I think you don't misunderstood. Good starting point: <https://opensource.stackexchange.com/questions/6813/is-using-the-gplv3-without-putting-a-license-notice-in-each-source-file-ok>.

It's advice/recommendation, not a requirement.

2023-11-06 17:17 UTC, Irineu333 commented
Regarding it being a recommendation, and not exactly a requirement, to put the license in the files, I understand perfectly. I decided to follow this recommendation, because the arguments convinced me. In the issue where the license is included, I mention exactly the same topic as the FAQ mentioned in this stackexchange issue #13. But regarding the issue of copyright, from what I understand, each file must mention the authors of the file and not the creator or maintainer of the project, which makes perfect sense. Look in the Linux repo, each file will have its authors mentioned and not Linus Torvalds.

2023-11-06 17:33 UTC, PatrykMis commented
Ok, so to rebase it or drop this commit?

2023-11-06 17:37 UTC, PatrykMis commented
also the second question, is it worth adding clause to some of the build files especially which are quite generic (without custom logic, Kotlin functions etc.)?

2023-11-06 18:09 UTC, Irineu333 commented
The recommendation is to put it in all files, even build files. I think the project is more coherent, maybe it's just a whim, but what's your opinion? I just wasn't putting it in the xml files.

If you want to leave it without a license that's fine, but if you want to include it, put your name. Even to receive credit for your work. In files where you have moved a lot, you can add your credits along with mine. From what I saw in the Linux repo, it may have more than one author.

2023-11-07 01:52 UTC, Irineu333 approved these changes

2023-11-07 01:52 UTC, Irineu333 commented on buildSrc/settings.gradle.kts
> + * Copyright (C) 2023 Irineu A. Silva.
This file is your copyright.

2023-11-07 01:52 UTC, Irineu333 commented on app/src/main/res/values-pl/strings.xml
> +  Copyright (C) 2023 Irineu A. Silva.
I think you were the creator of this file.

2023-11-07 01:52 UTC, Irineu333 commented on build.gradle.kts
> -buildscript {
Is it ok to remove this here? Do the repositories declared in buildSrc work for all modules?

2023-11-07 01:53 UTC, merged